import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import React from "react";

const dunbarLow = localFont({
  src: [
    {
      path: "../../public/fonts/dunbar-low/DunbarLow-Regular.woff2",
      weight: "400",
    },
    {
      path: "../../public/fonts/dunbar-low/DunbarLow-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-dunbar-low",
});

const noah = localFont({
  src: [
    {
      path: "../../public/fonts/noah/noah-regular.woff",
      weight: "400",
    },
    {
      path: "../../public/fonts/noah/noah-regularitalic.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/noah/noah-bold.woff",
      weight: "700",
    },
    {
      path: "../../public/fonts/noah/noah-bolditalic.woff",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-noah",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${dunbarLow.variable} ${noah.variable} font-sans h-full flex flex-col`}
      >
        <main className="flex-grow bg-base-100">{children}</main>
      </body>
    </html>
  );
}
